# APPLICATION
spring:
  application:
    name: Home On
    description: Projeto desenvolvido pelos alunos da Faculdade UNA de Uberlândia, sob orientação do professor @bbranquinho.
    version: @project.version@
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ

# SERVER
server:
  contextPath: /
  port: 8080
