# LOGGING
logging:
  file: target/home-on.log
  level:
    org.home.on: DEBUG
    org.springframework: INFO
    org.hibernate: INFO

# DATABASE
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/homeon
    username: root
    password: root
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
